apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Gateway API CRDs pinned in-repo for deterministic bootstrap
  - gateway-api-crds.yaml
  # NGINX Gateway Fabric CRDs
  - crds.yaml
  # NGINX Gateway Fabric rendered manifests
  - deploy.yaml
