kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  kubeProxyMode: "iptables"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30090
        hostPort: 30090
        protocol: TCP
      - containerPort: 30022
        hostPort: 30022
        protocol: TCP
      - containerPort: 31235
        hostPort: 31235
        protocol: TCP
      - containerPort: 30070
        hostPort: 3007
        protocol: TCP
      - containerPort: 30082
        hostPort: 8082
        protocol: TCP
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
      - containerPort: 30180
        hostPort: 8180
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
  - role: worker
