kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
  kubeProxyMode: "iptables"
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.configs."host.docker.internal:3000".tls]
      ca_file = "/etc/containerd/certs.d/host.docker.internal:3000/ca.crt"
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ./certs/ca.crt
        containerPath: /etc/containerd/certs.d/host.docker.internal:3000/ca.crt
        readOnly: true
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 31235
        hostPort: 31235
        protocol: TCP
      - containerPort: 30070
        hostPort: 3007
        protocol: TCP
      - containerPort: 30082
        hostPort: 8082
        protocol: TCP
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
      - containerPort: 30180
        hostPort: 8180
        protocol: TCP
  - role: worker
    extraMounts:
      - hostPath: ./certs/ca.crt
        containerPath: /etc/containerd/certs.d/host.docker.internal:3000/ca.crt
        readOnly: true
  - role: worker
    extraMounts:
      - hostPath: ./certs/ca.crt
        containerPath: /etc/containerd/certs.d/host.docker.internal:3000/ca.crt
        readOnly: true
  - role: worker
    extraMounts:
      - hostPath: ./certs/ca.crt
        containerPath: /etc/containerd/certs.d/host.docker.internal:3000/ca.crt
        readOnly: true
  - role: worker
    extraMounts:
      - hostPath: ./certs/ca.crt
        containerPath: /etc/containerd/certs.d/host.docker.internal:3000/ca.crt
        readOnly: true
