apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: sentiment

resources:
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - policies/cilium/cilium-network-policies.yaml
