apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: sentiment

resources:
  - sentiment-llm/ollama-pvc.yaml
  - sentiment-llm/ollama-deployment.yaml
  - sentiment-llm/ollama-service.yaml

  - sentiment/api-pvc.yaml
  - sentiment/api-deployment.yaml
  - sentiment/api-service.yaml

  - policies/cilium/cilium-network-policies.yaml
