apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - httproute-argocd.yaml
  - httproute-gitea.yaml
  - httproute-hubble.yaml
  - referencegrant-argocd.yaml
  - referencegrant-gitea.yaml
  - referencegrant-hubble.yaml
