apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac-signoz-bootstrap.yaml
  - httproute-argocd.yaml
  - httproute-gitea.yaml
  - httproute-hubble.yaml
  - httproute-keycloak.yaml
  - httproute-signoz.yaml
  - job-signoz-bootstrap.yaml
  - signoz-auth-proxy-configmap.yaml
  - signoz-auth-proxy-deployment.yaml
  - signoz-auth-proxy-service.yaml
  - oauth2-proxy-signoz-deployment.yaml
  - oauth2-proxy-signoz-service.yaml
  - referencegrant-argocd.yaml
  - referencegrant-gitea.yaml
  - referencegrant-hubble.yaml
  - referencegrant-signoz.yaml
  - http-to-https-snippetsfilter.yaml
  - keycloak-snippetsfilter.yaml
  - service-signoz-ui-nodeport.yaml
