apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: sentiment-auth

resources:
  - http-to-https-snippetsfilter.yaml
  - keycloak-snippetsfilter.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - policies/cilium/cilium-network-policies.yaml
