apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: azure-entraid-sim
commonLabels:
  app.kubernetes.io/part-of: azure-entraid-sim
resources:
  - namespace.yaml
  - keycloak-realm-config.yaml
  - keycloak-deployment.yaml
  - keycloak-service.yaml
  - reference-grant.yaml
  - policies/cilium/cilium-network-policies.yaml
