apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  labels:
    app.kubernetes.io/name: azurite
    app.kubernetes.io/component: storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: azurite
      app.kubernetes.io/component: storage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: azurite
        app.kubernetes.io/component: storage
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite:3.34.0
          imagePullPolicy: IfNotPresent
          args:
            - azurite
            - --location
            - /data
            - --blobHost
            - 0.0.0.0
            - --queueHost
            - 0.0.0.0
            - --tableHost
            - 0.0.0.0
          ports:
            - name: blob
              containerPort: 10000
            - name: queue
              containerPort: 10001
            - name: table
              containerPort: 10002
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          emptyDir: {}
