apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-deployment.yaml
  - api-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - gateway-service.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - gateway.yaml
  - policies/cilium/cilium-network-policies.yaml
  - ../secrets.yaml
