apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-deployment.yaml
  - api-service.yaml
  - azurite-deployment.yaml
  - azurite-service.yaml
  - telemetry-warmup-cronjob.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
  - keycloak-snippetsfilter.yaml
  - http-to-https-snippetsfilter.yaml
  - policies/cilium/cilium-network-policies.yaml
  - config.yaml
