apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: azure-auth-gateway
commonLabels:
  app.kubernetes.io/part-of: azure-auth-sim
resources:
  - gateway.yaml
  - gateway-service.yaml
  - nginxproxy.yaml
  - policies/cilium/cilium-network-policies.yaml
