apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: azure-auth-sim
commonLabels:
  app.kubernetes.io/part-of: azure-auth-sim
resources:
  - namespace.yaml
  - secrets.yaml
  - keycloak-realm-config.yaml
  - keycloak-deployment.yaml
  - keycloak-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - apim-deployment.yaml
  - apim-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - oauth2-proxy-deployment.yaml
  - oauth2-proxy-service.yaml
