apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: allow-gateway-routes
  namespace: sentiment-app
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: gateway-routes
  to:
    - group: ""
      kind: Service
      name: sentiment-frontend
    - group: ""
      kind: Service
      name: sentiment-api
