apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml
  - memberlist-secret.yaml
  - address-pool.yaml
  - l2-advertisement.yaml
