apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: azure-apim-sim
commonLabels:
  app.kubernetes.io/part-of: azure-apim-sim
resources:
  - secrets.yaml
  - apim-deployment.yaml
  - apim-service.yaml
  - apim-service-uat.yaml
  - apim-sentiment-deployment.yaml
  - apim-sentiment-service.yaml
  - apim-sentiment-service-uat.yaml
  - gateway.yaml
  - reference-grant.yaml
  - policies/cilium/cilium-network-policies.yaml
