apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-fastapi-keycloak
spec:
  template:
    spec:
      containers:
        - name: api-fastapi-keycloak
          env:
            - name: OIDC_ISSUER
              value: https://subnetcalc.uat.127.0.0.1.sslip.io/realms/subnet-calculator
            - name: CORS_ORIGINS
              value: https://subnetcalc.uat.127.0.0.1.sslip.io
