apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy-frontend
spec:
  template:
    spec:
      containers:
        - name: oauth2-proxy
          args:
            - --provider=oidc
            - --oidc-issuer-url=http://localhost:3008/realms/subnet-calculator
            - --client-id=frontend-app
            - --redirect-url=http://localhost:3008/oauth2/callback
            - --code-challenge-method=S256
            - --skip-oidc-discovery=true
            - --login-url=http://localhost:3008/realms/subnet-calculator/protocol/openid-connect/auth
            - --redeem-url=http://keycloak.azure-entraid-sim.svc.cluster.local:8080/realms/subnet-calculator/protocol/openid-connect/token
            - --oidc-jwks-url=http://keycloak.azure-entraid-sim.svc.cluster.local:8080/realms/subnet-calculator/protocol/openid-connect/certs
            - --validate-url=http://keycloak.azure-entraid-sim.svc.cluster.local:8080/realms/subnet-calculator/protocol/openid-connect/userinfo
            - --upstream=http://frontend-react-keycloak-protected
            - --http-address=0.0.0.0:4180
            - --cookie-secure=false
            - --cookie-httponly=true
            - --cookie-expire=4h
            - --cookie-refresh=1h
            - --cookie-name=_oauth2_proxy
            - --email-domain=*
            - --scope=openid user_impersonation
            - --pass-authorization-header=true
            - --pass-access-token=true
            - --pass-user-headers=true
            - --set-authorization-header=true
            - --set-xauthrequest=true
            - --standard-logging=true
            - --auth-logging=true
            - --request-logging=true
